name: Daily Electronics Deals Scraper

on:
  schedule:
    # Run daily at 8:00 AM UTC (11:00 AM EAT)
    - cron: '0 8 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape-deals:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run scraper
      run: node comprehensive_scraper.js
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update deals data - $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}